CREATE TABLE USERDATE (
NAME VARCHAR(255) PRIMARY KEY, 
PASS VARCHAR(255) NOT NULL, 
GENDER VARCHAR(255) NOT NULL, 
BIRTHDAY VARCHAR(255) NOT NULL, 
AGE INTEGER NOT NULL
);

CREATE TABLE BMI (
NAME VARCHAR(255),
DAY VARCHAR(255), 
HEIGHT INTEGER NOT NULL,
WEIGHT INTEGER NOT NULL,
MSG VARCHAR(255) NOT NULL, 
PRIMARY KEY (NAME,DAY),
FOREIGN KEY (NAME) REFERENCES USERDATE (NAME)
);

CREATE TABLE TODOLIST (
ID SERIAL,
NAME VARCHAR(255),
IMPORTANT INTEGER NOT NULL,
INFO VARCHAR(255) NOT NULL,
DEADLINE VARCHAR(255) NOT NULL,
MOMENTUM VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (NAME) REFERENCES USERDATE (NAME)
);